/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTeachersRouteImport } from './routes/_app.teachers'
import { Route as AppWorkshopsIndexRouteImport } from './routes/_app.workshops.index'
import { Route as AppWorkshopsNewRouteImport } from './routes/_app.workshops.new'
import { Route as AppWorkshopsIdIndexRouteImport } from './routes/_app.workshops.$id.index'
import { Route as AppWorkshopsIdEditRouteImport } from './routes/_app.workshops.$id.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeachersRoute = AppTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkshopsIndexRoute = AppWorkshopsIndexRouteImport.update({
  id: '/workshops/',
  path: '/workshops/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkshopsNewRoute = AppWorkshopsNewRouteImport.update({
  id: '/workshops/new',
  path: '/workshops/new',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkshopsIdIndexRoute = AppWorkshopsIdIndexRouteImport.update({
  id: '/workshops/$id/',
  path: '/workshops/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkshopsIdEditRoute = AppWorkshopsIdEditRouteImport.update({
  id: '/workshops/$id/edit',
  path: '/workshops/$id/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/teachers': typeof AppTeachersRoute
  '/workshops/new': typeof AppWorkshopsNewRoute
  '/workshops/': typeof AppWorkshopsIndexRoute
  '/workshops/$id/edit': typeof AppWorkshopsIdEditRoute
  '/workshops/$id/': typeof AppWorkshopsIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/teachers': typeof AppTeachersRoute
  '/': typeof AppIndexRoute
  '/workshops/new': typeof AppWorkshopsNewRoute
  '/workshops': typeof AppWorkshopsIndexRoute
  '/workshops/$id/edit': typeof AppWorkshopsIdEditRoute
  '/workshops/$id': typeof AppWorkshopsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/teachers': typeof AppTeachersRoute
  '/_app/': typeof AppIndexRoute
  '/_app/workshops/new': typeof AppWorkshopsNewRoute
  '/_app/workshops/': typeof AppWorkshopsIndexRoute
  '/_app/workshops/$id/edit': typeof AppWorkshopsIdEditRoute
  '/_app/workshops/$id/': typeof AppWorkshopsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/teachers'
    | '/workshops/new'
    | '/workshops/'
    | '/workshops/$id/edit'
    | '/workshops/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/teachers'
    | '/'
    | '/workshops/new'
    | '/workshops'
    | '/workshops/$id/edit'
    | '/workshops/$id'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/teachers'
    | '/_app/'
    | '/_app/workshops/new'
    | '/_app/workshops/'
    | '/_app/workshops/$id/edit'
    | '/_app/workshops/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teachers': {
      id: '/_app/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof AppTeachersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workshops/': {
      id: '/_app/workshops/'
      path: '/workshops'
      fullPath: '/workshops/'
      preLoaderRoute: typeof AppWorkshopsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workshops/new': {
      id: '/_app/workshops/new'
      path: '/workshops/new'
      fullPath: '/workshops/new'
      preLoaderRoute: typeof AppWorkshopsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workshops/$id/': {
      id: '/_app/workshops/$id/'
      path: '/workshops/$id'
      fullPath: '/workshops/$id/'
      preLoaderRoute: typeof AppWorkshopsIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workshops/$id/edit': {
      id: '/_app/workshops/$id/edit'
      path: '/workshops/$id/edit'
      fullPath: '/workshops/$id/edit'
      preLoaderRoute: typeof AppWorkshopsIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppTeachersRoute: typeof AppTeachersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppWorkshopsNewRoute: typeof AppWorkshopsNewRoute
  AppWorkshopsIndexRoute: typeof AppWorkshopsIndexRoute
  AppWorkshopsIdEditRoute: typeof AppWorkshopsIdEditRoute
  AppWorkshopsIdIndexRoute: typeof AppWorkshopsIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppTeachersRoute: AppTeachersRoute,
  AppIndexRoute: AppIndexRoute,
  AppWorkshopsNewRoute: AppWorkshopsNewRoute,
  AppWorkshopsIndexRoute: AppWorkshopsIndexRoute,
  AppWorkshopsIdEditRoute: AppWorkshopsIdEditRoute,
  AppWorkshopsIdIndexRoute: AppWorkshopsIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
